server:
  port: 8082

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/restaurant_db
    url: jdbc:mysql://localhost:3306/food_court_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  appDescription: "Service Restaurant"
  appVersion: "1.0.0"



users:
  service:
    url: http://localhost:8081

jwt:
  secret: ${ACCESS_TOKEN_SECRET:Zy1vNcA3rBpX7LsGt49qWeJkMmPnRtUv}

  logging:
    level:
      org:
        springframework:
          security: DEBUG
